/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedClientRouteImport } from './routes/_authenticated/_client'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPendingRouteImport } from './routes/_authenticated/pending'
import { Route as AuthenticatedClientBillingRouteImport } from './routes/_authenticated/_client/billing'
import { Route as AuthenticatedClientDashboardRouteImport } from './routes/_authenticated/_client/dashboard'
import { Route as AuthenticatedClientDocumentsRouteImport } from './routes/_authenticated/_client/documents'
import { Route as AuthenticatedClientOrdersRouteImport } from './routes/_authenticated/_client/orders'
import { Route as AuthenticatedClientProductsRouteImport } from './routes/_authenticated/_client/products'
import { Route as AuthenticatedClientWalletRouteImport } from './routes/_authenticated/_client/wallet'
import { Route as AuthenticatedAdminClientsRouteImport } from './routes/_authenticated/admin/clients'
import { Route as AuthenticatedAdminDocumentsRouteImport } from './routes/_authenticated/admin/documents'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin/products'
import { Route as AuthenticatedAdminWalletRouteImport } from './routes/_authenticated/admin/wallet'
import { Route as AuthenticatedClientQuotesIndexRouteImport } from './routes/_authenticated/_client/quotes/index'
import { Route as AuthenticatedClientQuotesIdRouteImport } from './routes/_authenticated/_client/quotes/$id'
import { Route as AuthenticatedClientQuotesNewRouteImport } from './routes/_authenticated/_client/quotes/new'
import { Route as AuthenticatedAdminQuotesIndexRouteImport } from './routes/_authenticated/admin/quotes/index'
import { Route as AuthenticatedAdminQuotesIdRouteImport } from './routes/_authenticated/admin/quotes/$id'
import { Route as ApiPublicCronAutoTopupRouteImport } from './routes/api/public/cron/auto-topup'
import { Route as ApiPublicCronDocumentsSweepRouteImport } from './routes/api/public/cron/documents-sweep'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClientRoute = AuthenticatedClientRouteImport.update({
  id: '/_client',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPendingRoute = AuthenticatedPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientBillingRoute =
  AuthenticatedClientBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedClientDashboardRoute =
  AuthenticatedClientDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedClientDocumentsRoute =
  AuthenticatedClientDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedClientOrdersRoute =
  AuthenticatedClientOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedClientProductsRoute =
  AuthenticatedClientProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedClientWalletRoute =
  AuthenticatedClientWalletRouteImport.update({
    id: '/wallet',
    path: '/wallet',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedAdminClientsRoute =
  AuthenticatedAdminClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDocumentsRoute =
  AuthenticatedAdminDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminWalletRoute =
  AuthenticatedAdminWalletRouteImport.update({
    id: '/wallet',
    path: '/wallet',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedClientQuotesIndexRoute =
  AuthenticatedClientQuotesIndexRouteImport.update({
    id: '/quotes/',
    path: '/quotes/',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedClientQuotesIdRoute =
  AuthenticatedClientQuotesIdRouteImport.update({
    id: '/quotes/$id',
    path: '/quotes/$id',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedClientQuotesNewRoute =
  AuthenticatedClientQuotesNewRouteImport.update({
    id: '/quotes/new',
    path: '/quotes/new',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedAdminQuotesIndexRoute =
  AuthenticatedAdminQuotesIndexRouteImport.update({
    id: '/quotes/',
    path: '/quotes/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminQuotesIdRoute =
  AuthenticatedAdminQuotesIdRouteImport.update({
    id: '/quotes/$id',
    path: '/quotes/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicCronAutoTopupRoute = ApiPublicCronAutoTopupRouteImport.update({
  id: '/api/public/cron/auto-topup',
  path: '/api/public/cron/auto-topup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronDocumentsSweepRoute =
  ApiPublicCronDocumentsSweepRouteImport.update({
    id: '/api/public/cron/documents-sweep',
    path: '/api/public/cron/documents-sweep',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/pending': typeof AuthenticatedPendingRoute
  '/billing': typeof AuthenticatedClientBillingRoute
  '/dashboard': typeof AuthenticatedClientDashboardRoute
  '/documents': typeof AuthenticatedClientDocumentsRoute
  '/orders': typeof AuthenticatedClientOrdersRoute
  '/products': typeof AuthenticatedClientProductsRoute
  '/wallet': typeof AuthenticatedClientWalletRoute
  '/admin/clients': typeof AuthenticatedAdminClientsRoute
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/wallet': typeof AuthenticatedAdminWalletRoute
  '/quotes/$id': typeof AuthenticatedClientQuotesIdRoute
  '/quotes/new': typeof AuthenticatedClientQuotesNewRoute
  '/admin/quotes/$id': typeof AuthenticatedAdminQuotesIdRoute
  '/api/public/cron/auto-topup': typeof ApiPublicCronAutoTopupRoute
  '/api/public/cron/documents-sweep': typeof ApiPublicCronDocumentsSweepRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/quotes/': typeof AuthenticatedClientQuotesIndexRoute
  '/admin/quotes/': typeof AuthenticatedAdminQuotesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/pending': typeof AuthenticatedPendingRoute
  '/billing': typeof AuthenticatedClientBillingRoute
  '/dashboard': typeof AuthenticatedClientDashboardRoute
  '/documents': typeof AuthenticatedClientDocumentsRoute
  '/orders': typeof AuthenticatedClientOrdersRoute
  '/products': typeof AuthenticatedClientProductsRoute
  '/wallet': typeof AuthenticatedClientWalletRoute
  '/admin/clients': typeof AuthenticatedAdminClientsRoute
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/wallet': typeof AuthenticatedAdminWalletRoute
  '/quotes/$id': typeof AuthenticatedClientQuotesIdRoute
  '/quotes/new': typeof AuthenticatedClientQuotesNewRoute
  '/admin/quotes/$id': typeof AuthenticatedAdminQuotesIdRoute
  '/api/public/cron/auto-topup': typeof ApiPublicCronAutoTopupRoute
  '/api/public/cron/documents-sweep': typeof ApiPublicCronDocumentsSweepRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/quotes': typeof AuthenticatedClientQuotesIndexRoute
  '/admin/quotes': typeof AuthenticatedAdminQuotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/_client': typeof AuthenticatedClientRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/pending': typeof AuthenticatedPendingRoute
  '/_authenticated/_client/billing': typeof AuthenticatedClientBillingRoute
  '/_authenticated/_client/dashboard': typeof AuthenticatedClientDashboardRoute
  '/_authenticated/_client/documents': typeof AuthenticatedClientDocumentsRoute
  '/_authenticated/_client/orders': typeof AuthenticatedClientOrdersRoute
  '/_authenticated/_client/products': typeof AuthenticatedClientProductsRoute
  '/_authenticated/_client/wallet': typeof AuthenticatedClientWalletRoute
  '/_authenticated/admin/clients': typeof AuthenticatedAdminClientsRoute
  '/_authenticated/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/admin/wallet': typeof AuthenticatedAdminWalletRoute
  '/_authenticated/_client/quotes/$id': typeof AuthenticatedClientQuotesIdRoute
  '/_authenticated/_client/quotes/new': typeof AuthenticatedClientQuotesNewRoute
  '/_authenticated/admin/quotes/$id': typeof AuthenticatedAdminQuotesIdRoute
  '/api/public/cron/auto-topup': typeof ApiPublicCronAutoTopupRoute
  '/api/public/cron/documents-sweep': typeof ApiPublicCronDocumentsSweepRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/_authenticated/_client/quotes/': typeof AuthenticatedClientQuotesIndexRoute
  '/_authenticated/admin/quotes/': typeof AuthenticatedAdminQuotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/pending'
    | '/billing'
    | '/dashboard'
    | '/documents'
    | '/orders'
    | '/products'
    | '/wallet'
    | '/admin/clients'
    | '/admin/documents'
    | '/admin/products'
    | '/admin/wallet'
    | '/quotes/$id'
    | '/quotes/new'
    | '/admin/quotes/$id'
    | '/api/public/cron/auto-topup'
    | '/api/public/cron/documents-sweep'
    | '/api/public/payments/webhook'
    | '/quotes/'
    | '/admin/quotes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/pending'
    | '/billing'
    | '/dashboard'
    | '/documents'
    | '/orders'
    | '/products'
    | '/wallet'
    | '/admin/clients'
    | '/admin/documents'
    | '/admin/products'
    | '/admin/wallet'
    | '/quotes/$id'
    | '/quotes/new'
    | '/admin/quotes/$id'
    | '/api/public/cron/auto-topup'
    | '/api/public/cron/documents-sweep'
    | '/api/public/payments/webhook'
    | '/quotes'
    | '/admin/quotes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/_client'
    | '/_authenticated/admin'
    | '/_authenticated/pending'
    | '/_authenticated/_client/billing'
    | '/_authenticated/_client/dashboard'
    | '/_authenticated/_client/documents'
    | '/_authenticated/_client/orders'
    | '/_authenticated/_client/products'
    | '/_authenticated/_client/wallet'
    | '/_authenticated/admin/clients'
    | '/_authenticated/admin/documents'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/wallet'
    | '/_authenticated/_client/quotes/$id'
    | '/_authenticated/_client/quotes/new'
    | '/_authenticated/admin/quotes/$id'
    | '/api/public/cron/auto-topup'
    | '/api/public/cron/documents-sweep'
    | '/api/public/payments/webhook'
    | '/_authenticated/_client/quotes/'
    | '/_authenticated/admin/quotes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicCronAutoTopupRoute: typeof ApiPublicCronAutoTopupRoute
  ApiPublicCronDocumentsSweepRoute: typeof ApiPublicCronDocumentsSweepRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_client': {
      id: '/_authenticated/_client'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedClientRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pending': {
      id: '/_authenticated/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof AuthenticatedPendingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_client/billing': {
      id: '/_authenticated/_client/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedClientBillingRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/_client/dashboard': {
      id: '/_authenticated/_client/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedClientDashboardRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/_client/documents': {
      id: '/_authenticated/_client/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedClientDocumentsRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/_client/orders': {
      id: '/_authenticated/_client/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedClientOrdersRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/_client/products': {
      id: '/_authenticated/_client/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedClientProductsRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/_client/wallet': {
      id: '/_authenticated/_client/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedClientWalletRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/admin/clients': {
      id: '/_authenticated/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AuthenticatedAdminClientsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/documents': {
      id: '/_authenticated/admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AuthenticatedAdminDocumentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/wallet': {
      id: '/_authenticated/admin/wallet'
      path: '/wallet'
      fullPath: '/admin/wallet'
      preLoaderRoute: typeof AuthenticatedAdminWalletRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_client/quotes/': {
      id: '/_authenticated/_client/quotes/'
      path: '/quotes'
      fullPath: '/quotes/'
      preLoaderRoute: typeof AuthenticatedClientQuotesIndexRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/_client/quotes/$id': {
      id: '/_authenticated/_client/quotes/$id'
      path: '/quotes/$id'
      fullPath: '/quotes/$id'
      preLoaderRoute: typeof AuthenticatedClientQuotesIdRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/_client/quotes/new': {
      id: '/_authenticated/_client/quotes/new'
      path: '/quotes/new'
      fullPath: '/quotes/new'
      preLoaderRoute: typeof AuthenticatedClientQuotesNewRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/admin/quotes/': {
      id: '/_authenticated/admin/quotes/'
      path: '/quotes'
      fullPath: '/admin/quotes/'
      preLoaderRoute: typeof AuthenticatedAdminQuotesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/quotes/$id': {
      id: '/_authenticated/admin/quotes/$id'
      path: '/quotes/$id'
      fullPath: '/admin/quotes/$id'
      preLoaderRoute: typeof AuthenticatedAdminQuotesIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/cron/auto-topup': {
      id: '/api/public/cron/auto-topup'
      path: '/api/public/cron/auto-topup'
      fullPath: '/api/public/cron/auto-topup'
      preLoaderRoute: typeof ApiPublicCronAutoTopupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/documents-sweep': {
      id: '/api/public/cron/documents-sweep'
      path: '/api/public/cron/documents-sweep'
      fullPath: '/api/public/cron/documents-sweep'
      preLoaderRoute: typeof ApiPublicCronDocumentsSweepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedClientRouteChildren {
  AuthenticatedClientBillingRoute: typeof AuthenticatedClientBillingRoute
  AuthenticatedClientDashboardRoute: typeof AuthenticatedClientDashboardRoute
  AuthenticatedClientDocumentsRoute: typeof AuthenticatedClientDocumentsRoute
  AuthenticatedClientOrdersRoute: typeof AuthenticatedClientOrdersRoute
  AuthenticatedClientProductsRoute: typeof AuthenticatedClientProductsRoute
  AuthenticatedClientWalletRoute: typeof AuthenticatedClientWalletRoute
  AuthenticatedClientQuotesIdRoute: typeof AuthenticatedClientQuotesIdRoute
  AuthenticatedClientQuotesNewRoute: typeof AuthenticatedClientQuotesNewRoute
  AuthenticatedClientQuotesIndexRoute: typeof AuthenticatedClientQuotesIndexRoute
}

const AuthenticatedClientRouteChildren: AuthenticatedClientRouteChildren = {
  AuthenticatedClientBillingRoute: AuthenticatedClientBillingRoute,
  AuthenticatedClientDashboardRoute: AuthenticatedClientDashboardRoute,
  AuthenticatedClientDocumentsRoute: AuthenticatedClientDocumentsRoute,
  AuthenticatedClientOrdersRoute: AuthenticatedClientOrdersRoute,
  AuthenticatedClientProductsRoute: AuthenticatedClientProductsRoute,
  AuthenticatedClientWalletRoute: AuthenticatedClientWalletRoute,
  AuthenticatedClientQuotesIdRoute: AuthenticatedClientQuotesIdRoute,
  AuthenticatedClientQuotesNewRoute: AuthenticatedClientQuotesNewRoute,
  AuthenticatedClientQuotesIndexRoute: AuthenticatedClientQuotesIndexRoute,
}

const AuthenticatedClientRouteWithChildren =
  AuthenticatedClientRoute._addFileChildren(AuthenticatedClientRouteChildren)

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminClientsRoute: typeof AuthenticatedAdminClientsRoute
  AuthenticatedAdminDocumentsRoute: typeof AuthenticatedAdminDocumentsRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminWalletRoute: typeof AuthenticatedAdminWalletRoute
  AuthenticatedAdminQuotesIdRoute: typeof AuthenticatedAdminQuotesIdRoute
  AuthenticatedAdminQuotesIndexRoute: typeof AuthenticatedAdminQuotesIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminClientsRoute: AuthenticatedAdminClientsRoute,
  AuthenticatedAdminDocumentsRoute: AuthenticatedAdminDocumentsRoute,
  AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
  AuthenticatedAdminWalletRoute: AuthenticatedAdminWalletRoute,
  AuthenticatedAdminQuotesIdRoute: AuthenticatedAdminQuotesIdRoute,
  AuthenticatedAdminQuotesIndexRoute: AuthenticatedAdminQuotesIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClientRoute: typeof AuthenticatedClientRouteWithChildren
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedPendingRoute: typeof AuthenticatedPendingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClientRoute: AuthenticatedClientRouteWithChildren,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedPendingRoute: AuthenticatedPendingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicCronAutoTopupRoute: ApiPublicCronAutoTopupRoute,
  ApiPublicCronDocumentsSweepRoute: ApiPublicCronDocumentsSweepRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
