/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedClientRouteImport } from './routes/_authenticated/_client'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPendingRouteImport } from './routes/_authenticated/pending'
import { Route as AuthenticatedClientBillingRouteImport } from './routes/_authenticated/_client/billing'
import { Route as AuthenticatedClientDashboardRouteImport } from './routes/_authenticated/_client/dashboard'
import { Route as AuthenticatedClientDisputesRouteImport } from './routes/_authenticated/_client/disputes'
import { Route as AuthenticatedClientDocumentsRouteImport } from './routes/_authenticated/_client/documents'
import { Route as AuthenticatedClientProductsRouteImport } from './routes/_authenticated/_client/products'
import { Route as AuthenticatedClientSpymarketRouteImport } from './routes/_authenticated/_client/spymarket'
import { Route as AuthenticatedClientWalletRouteImport } from './routes/_authenticated/_client/wallet'
import { Route as AuthenticatedClientWorkspacesRouteImport } from './routes/_authenticated/_client/workspaces'
import { Route as AuthenticatedAdminClientsRouteImport } from './routes/_authenticated/admin/clients'
import { Route as AuthenticatedAdminDisputesRouteImport } from './routes/_authenticated/admin/disputes'
import { Route as AuthenticatedAdminDocumentsRouteImport } from './routes/_authenticated/admin/documents'
import { Route as AuthenticatedAdminEntitiesRouteImport } from './routes/_authenticated/admin/entities'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin/orders'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin/products'
import { Route as AuthenticatedAdminSpymarketRouteImport } from './routes/_authenticated/admin/spymarket'
import { Route as AuthenticatedAdminSpymarketToolsRouteImport } from './routes/_authenticated/admin/spymarket-tools'
import { Route as AuthenticatedAdminWalletRouteImport } from './routes/_authenticated/admin/wallet'
import { Route as AuthenticatedClientDisputesIdRouteImport } from './routes/_authenticated/_client/disputes.$id'
import { Route as AuthenticatedClientOrdersIndexRouteImport } from './routes/_authenticated/_client/orders/index'
import { Route as AuthenticatedClientOrdersIdRouteImport } from './routes/_authenticated/_client/orders.$id'
import { Route as AuthenticatedClientOrdersImportRouteImport } from './routes/_authenticated/_client/orders/import'
import { Route as AuthenticatedClientOrdersNewRouteImport } from './routes/_authenticated/_client/orders/new'
import { Route as AuthenticatedClientQuotesIndexRouteImport } from './routes/_authenticated/_client/quotes/index'
import { Route as AuthenticatedClientQuotesIdRouteImport } from './routes/_authenticated/_client/quotes/$id'
import { Route as AuthenticatedClientQuotesNewRouteImport } from './routes/_authenticated/_client/quotes/new'
import { Route as AuthenticatedClientWorkspacesNewRouteImport } from './routes/_authenticated/_client/workspaces/new'
import { Route as AuthenticatedAdminDisputesIdRouteImport } from './routes/_authenticated/admin/disputes.$id'
import { Route as AuthenticatedAdminQuotesIndexRouteImport } from './routes/_authenticated/admin/quotes/index'
import { Route as AuthenticatedAdminQuotesIdRouteImport } from './routes/_authenticated/admin/quotes/$id'
import { Route as ApiPublicCronAutoTopupRouteImport } from './routes/api/public/cron/auto-topup'
import { Route as ApiPublicCronDocumentsSweepRouteImport } from './routes/api/public/cron/documents-sweep'
import { Route as ApiPublicCronOrderExpiryRouteImport } from './routes/api/public/cron/order-expiry'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClientRoute = AuthenticatedClientRouteImport.update({
  id: '/_client',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPendingRoute = AuthenticatedPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientBillingRoute =
  AuthenticatedClientBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedClientDashboardRoute =
  AuthenticatedClientDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedClientDisputesRoute =
  AuthenticatedClientDisputesRouteImport.update({
    id: '/disputes',
    path: '/disputes',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedClientDocumentsRoute =
  AuthenticatedClientDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedClientProductsRoute =
  AuthenticatedClientProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedClientSpymarketRoute =
  AuthenticatedClientSpymarketRouteImport.update({
    id: '/spymarket',
    path: '/spymarket',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedClientWalletRoute =
  AuthenticatedClientWalletRouteImport.update({
    id: '/wallet',
    path: '/wallet',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedClientWorkspacesRoute =
  AuthenticatedClientWorkspacesRouteImport.update({
    id: '/workspaces',
    path: '/workspaces',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedAdminClientsRoute =
  AuthenticatedAdminClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDisputesRoute =
  AuthenticatedAdminDisputesRouteImport.update({
    id: '/disputes',
    path: '/disputes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDocumentsRoute =
  AuthenticatedAdminDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEntitiesRoute =
  AuthenticatedAdminEntitiesRouteImport.update({
    id: '/entities',
    path: '/entities',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSpymarketRoute =
  AuthenticatedAdminSpymarketRouteImport.update({
    id: '/spymarket',
    path: '/spymarket',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSpymarketToolsRoute =
  AuthenticatedAdminSpymarketToolsRouteImport.update({
    id: '/spymarket-tools',
    path: '/spymarket-tools',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminWalletRoute =
  AuthenticatedAdminWalletRouteImport.update({
    id: '/wallet',
    path: '/wallet',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedClientDisputesIdRoute =
  AuthenticatedClientDisputesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedClientDisputesRoute,
  } as any)
const AuthenticatedClientOrdersIndexRoute =
  AuthenticatedClientOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedClientOrdersIdRoute =
  AuthenticatedClientOrdersIdRouteImport.update({
    id: '/orders/$id',
    path: '/orders/$id',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedClientOrdersImportRoute =
  AuthenticatedClientOrdersImportRouteImport.update({
    id: '/orders/import',
    path: '/orders/import',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedClientOrdersNewRoute =
  AuthenticatedClientOrdersNewRouteImport.update({
    id: '/orders/new',
    path: '/orders/new',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedClientQuotesIndexRoute =
  AuthenticatedClientQuotesIndexRouteImport.update({
    id: '/quotes/',
    path: '/quotes/',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedClientQuotesIdRoute =
  AuthenticatedClientQuotesIdRouteImport.update({
    id: '/quotes/$id',
    path: '/quotes/$id',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedClientQuotesNewRoute =
  AuthenticatedClientQuotesNewRouteImport.update({
    id: '/quotes/new',
    path: '/quotes/new',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedClientWorkspacesNewRoute =
  AuthenticatedClientWorkspacesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedClientWorkspacesRoute,
  } as any)
const AuthenticatedAdminDisputesIdRoute =
  AuthenticatedAdminDisputesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminDisputesRoute,
  } as any)
const AuthenticatedAdminQuotesIndexRoute =
  AuthenticatedAdminQuotesIndexRouteImport.update({
    id: '/quotes/',
    path: '/quotes/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminQuotesIdRoute =
  AuthenticatedAdminQuotesIdRouteImport.update({
    id: '/quotes/$id',
    path: '/quotes/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicCronAutoTopupRoute = ApiPublicCronAutoTopupRouteImport.update({
  id: '/api/public/cron/auto-topup',
  path: '/api/public/cron/auto-topup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronDocumentsSweepRoute =
  ApiPublicCronDocumentsSweepRouteImport.update({
    id: '/api/public/cron/documents-sweep',
    path: '/api/public/cron/documents-sweep',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronOrderExpiryRoute =
  ApiPublicCronOrderExpiryRouteImport.update({
    id: '/api/public/cron/order-expiry',
    path: '/api/public/cron/order-expiry',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/pending': typeof AuthenticatedPendingRoute
  '/billing': typeof AuthenticatedClientBillingRoute
  '/dashboard': typeof AuthenticatedClientDashboardRoute
  '/disputes': typeof AuthenticatedClientDisputesRouteWithChildren
  '/documents': typeof AuthenticatedClientDocumentsRoute
  '/products': typeof AuthenticatedClientProductsRoute
  '/spymarket': typeof AuthenticatedClientSpymarketRoute
  '/wallet': typeof AuthenticatedClientWalletRoute
  '/workspaces': typeof AuthenticatedClientWorkspacesRouteWithChildren
  '/admin/clients': typeof AuthenticatedAdminClientsRoute
  '/admin/disputes': typeof AuthenticatedAdminDisputesRouteWithChildren
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/admin/entities': typeof AuthenticatedAdminEntitiesRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/spymarket': typeof AuthenticatedAdminSpymarketRoute
  '/admin/spymarket-tools': typeof AuthenticatedAdminSpymarketToolsRoute
  '/admin/wallet': typeof AuthenticatedAdminWalletRoute
  '/disputes/$id': typeof AuthenticatedClientDisputesIdRoute
  '/orders/$id': typeof AuthenticatedClientOrdersIdRoute
  '/orders/import': typeof AuthenticatedClientOrdersImportRoute
  '/orders/new': typeof AuthenticatedClientOrdersNewRoute
  '/quotes/$id': typeof AuthenticatedClientQuotesIdRoute
  '/quotes/new': typeof AuthenticatedClientQuotesNewRoute
  '/workspaces/new': typeof AuthenticatedClientWorkspacesNewRoute
  '/admin/disputes/$id': typeof AuthenticatedAdminDisputesIdRoute
  '/admin/quotes/$id': typeof AuthenticatedAdminQuotesIdRoute
  '/api/public/cron/auto-topup': typeof ApiPublicCronAutoTopupRoute
  '/api/public/cron/documents-sweep': typeof ApiPublicCronDocumentsSweepRoute
  '/api/public/cron/order-expiry': typeof ApiPublicCronOrderExpiryRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/orders/': typeof AuthenticatedClientOrdersIndexRoute
  '/quotes/': typeof AuthenticatedClientQuotesIndexRoute
  '/admin/quotes/': typeof AuthenticatedAdminQuotesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/pending': typeof AuthenticatedPendingRoute
  '/billing': typeof AuthenticatedClientBillingRoute
  '/dashboard': typeof AuthenticatedClientDashboardRoute
  '/disputes': typeof AuthenticatedClientDisputesRouteWithChildren
  '/documents': typeof AuthenticatedClientDocumentsRoute
  '/products': typeof AuthenticatedClientProductsRoute
  '/spymarket': typeof AuthenticatedClientSpymarketRoute
  '/wallet': typeof AuthenticatedClientWalletRoute
  '/workspaces': typeof AuthenticatedClientWorkspacesRouteWithChildren
  '/admin/clients': typeof AuthenticatedAdminClientsRoute
  '/admin/disputes': typeof AuthenticatedAdminDisputesRouteWithChildren
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/admin/entities': typeof AuthenticatedAdminEntitiesRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/spymarket': typeof AuthenticatedAdminSpymarketRoute
  '/admin/spymarket-tools': typeof AuthenticatedAdminSpymarketToolsRoute
  '/admin/wallet': typeof AuthenticatedAdminWalletRoute
  '/disputes/$id': typeof AuthenticatedClientDisputesIdRoute
  '/orders/$id': typeof AuthenticatedClientOrdersIdRoute
  '/orders/import': typeof AuthenticatedClientOrdersImportRoute
  '/orders/new': typeof AuthenticatedClientOrdersNewRoute
  '/quotes/$id': typeof AuthenticatedClientQuotesIdRoute
  '/quotes/new': typeof AuthenticatedClientQuotesNewRoute
  '/workspaces/new': typeof AuthenticatedClientWorkspacesNewRoute
  '/admin/disputes/$id': typeof AuthenticatedAdminDisputesIdRoute
  '/admin/quotes/$id': typeof AuthenticatedAdminQuotesIdRoute
  '/api/public/cron/auto-topup': typeof ApiPublicCronAutoTopupRoute
  '/api/public/cron/documents-sweep': typeof ApiPublicCronDocumentsSweepRoute
  '/api/public/cron/order-expiry': typeof ApiPublicCronOrderExpiryRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/orders': typeof AuthenticatedClientOrdersIndexRoute
  '/quotes': typeof AuthenticatedClientQuotesIndexRoute
  '/admin/quotes': typeof AuthenticatedAdminQuotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_authenticated/_client': typeof AuthenticatedClientRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/pending': typeof AuthenticatedPendingRoute
  '/_authenticated/_client/billing': typeof AuthenticatedClientBillingRoute
  '/_authenticated/_client/dashboard': typeof AuthenticatedClientDashboardRoute
  '/_authenticated/_client/disputes': typeof AuthenticatedClientDisputesRouteWithChildren
  '/_authenticated/_client/documents': typeof AuthenticatedClientDocumentsRoute
  '/_authenticated/_client/products': typeof AuthenticatedClientProductsRoute
  '/_authenticated/_client/spymarket': typeof AuthenticatedClientSpymarketRoute
  '/_authenticated/_client/wallet': typeof AuthenticatedClientWalletRoute
  '/_authenticated/_client/workspaces': typeof AuthenticatedClientWorkspacesRouteWithChildren
  '/_authenticated/admin/clients': typeof AuthenticatedAdminClientsRoute
  '/_authenticated/admin/disputes': typeof AuthenticatedAdminDisputesRouteWithChildren
  '/_authenticated/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/_authenticated/admin/entities': typeof AuthenticatedAdminEntitiesRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/admin/spymarket': typeof AuthenticatedAdminSpymarketRoute
  '/_authenticated/admin/spymarket-tools': typeof AuthenticatedAdminSpymarketToolsRoute
  '/_authenticated/admin/wallet': typeof AuthenticatedAdminWalletRoute
  '/_authenticated/_client/disputes/$id': typeof AuthenticatedClientDisputesIdRoute
  '/_authenticated/_client/orders/$id': typeof AuthenticatedClientOrdersIdRoute
  '/_authenticated/_client/orders/import': typeof AuthenticatedClientOrdersImportRoute
  '/_authenticated/_client/orders/new': typeof AuthenticatedClientOrdersNewRoute
  '/_authenticated/_client/quotes/$id': typeof AuthenticatedClientQuotesIdRoute
  '/_authenticated/_client/quotes/new': typeof AuthenticatedClientQuotesNewRoute
  '/_authenticated/_client/workspaces/new': typeof AuthenticatedClientWorkspacesNewRoute
  '/_authenticated/admin/disputes/$id': typeof AuthenticatedAdminDisputesIdRoute
  '/_authenticated/admin/quotes/$id': typeof AuthenticatedAdminQuotesIdRoute
  '/api/public/cron/auto-topup': typeof ApiPublicCronAutoTopupRoute
  '/api/public/cron/documents-sweep': typeof ApiPublicCronDocumentsSweepRoute
  '/api/public/cron/order-expiry': typeof ApiPublicCronOrderExpiryRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/_authenticated/_client/orders/': typeof AuthenticatedClientOrdersIndexRoute
  '/_authenticated/_client/quotes/': typeof AuthenticatedClientQuotesIndexRoute
  '/_authenticated/admin/quotes/': typeof AuthenticatedAdminQuotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/admin'
    | '/pending'
    | '/billing'
    | '/dashboard'
    | '/disputes'
    | '/documents'
    | '/products'
    | '/spymarket'
    | '/wallet'
    | '/workspaces'
    | '/admin/clients'
    | '/admin/disputes'
    | '/admin/documents'
    | '/admin/entities'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/spymarket'
    | '/admin/spymarket-tools'
    | '/admin/wallet'
    | '/disputes/$id'
    | '/orders/$id'
    | '/orders/import'
    | '/orders/new'
    | '/quotes/$id'
    | '/quotes/new'
    | '/workspaces/new'
    | '/admin/disputes/$id'
    | '/admin/quotes/$id'
    | '/api/public/cron/auto-topup'
    | '/api/public/cron/documents-sweep'
    | '/api/public/cron/order-expiry'
    | '/api/public/payments/webhook'
    | '/orders/'
    | '/quotes/'
    | '/admin/quotes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/admin'
    | '/pending'
    | '/billing'
    | '/dashboard'
    | '/disputes'
    | '/documents'
    | '/products'
    | '/spymarket'
    | '/wallet'
    | '/workspaces'
    | '/admin/clients'
    | '/admin/disputes'
    | '/admin/documents'
    | '/admin/entities'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/spymarket'
    | '/admin/spymarket-tools'
    | '/admin/wallet'
    | '/disputes/$id'
    | '/orders/$id'
    | '/orders/import'
    | '/orders/new'
    | '/quotes/$id'
    | '/quotes/new'
    | '/workspaces/new'
    | '/admin/disputes/$id'
    | '/admin/quotes/$id'
    | '/api/public/cron/auto-topup'
    | '/api/public/cron/documents-sweep'
    | '/api/public/cron/order-expiry'
    | '/api/public/payments/webhook'
    | '/orders'
    | '/quotes'
    | '/admin/quotes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/_authenticated/_client'
    | '/_authenticated/admin'
    | '/_authenticated/pending'
    | '/_authenticated/_client/billing'
    | '/_authenticated/_client/dashboard'
    | '/_authenticated/_client/disputes'
    | '/_authenticated/_client/documents'
    | '/_authenticated/_client/products'
    | '/_authenticated/_client/spymarket'
    | '/_authenticated/_client/wallet'
    | '/_authenticated/_client/workspaces'
    | '/_authenticated/admin/clients'
    | '/_authenticated/admin/disputes'
    | '/_authenticated/admin/documents'
    | '/_authenticated/admin/entities'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/spymarket'
    | '/_authenticated/admin/spymarket-tools'
    | '/_authenticated/admin/wallet'
    | '/_authenticated/_client/disputes/$id'
    | '/_authenticated/_client/orders/$id'
    | '/_authenticated/_client/orders/import'
    | '/_authenticated/_client/orders/new'
    | '/_authenticated/_client/quotes/$id'
    | '/_authenticated/_client/quotes/new'
    | '/_authenticated/_client/workspaces/new'
    | '/_authenticated/admin/disputes/$id'
    | '/_authenticated/admin/quotes/$id'
    | '/api/public/cron/auto-topup'
    | '/api/public/cron/documents-sweep'
    | '/api/public/cron/order-expiry'
    | '/api/public/payments/webhook'
    | '/_authenticated/_client/orders/'
    | '/_authenticated/_client/quotes/'
    | '/_authenticated/admin/quotes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  ApiPublicCronAutoTopupRoute: typeof ApiPublicCronAutoTopupRoute
  ApiPublicCronDocumentsSweepRoute: typeof ApiPublicCronDocumentsSweepRoute
  ApiPublicCronOrderExpiryRoute: typeof ApiPublicCronOrderExpiryRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_client': {
      id: '/_authenticated/_client'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedClientRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pending': {
      id: '/_authenticated/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof AuthenticatedPendingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_client/billing': {
      id: '/_authenticated/_client/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedClientBillingRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/_client/dashboard': {
      id: '/_authenticated/_client/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedClientDashboardRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/_client/disputes': {
      id: '/_authenticated/_client/disputes'
      path: '/disputes'
      fullPath: '/disputes'
      preLoaderRoute: typeof AuthenticatedClientDisputesRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/_client/documents': {
      id: '/_authenticated/_client/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedClientDocumentsRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/_client/products': {
      id: '/_authenticated/_client/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedClientProductsRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/_client/spymarket': {
      id: '/_authenticated/_client/spymarket'
      path: '/spymarket'
      fullPath: '/spymarket'
      preLoaderRoute: typeof AuthenticatedClientSpymarketRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/_client/wallet': {
      id: '/_authenticated/_client/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedClientWalletRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/_client/workspaces': {
      id: '/_authenticated/_client/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof AuthenticatedClientWorkspacesRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/admin/clients': {
      id: '/_authenticated/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AuthenticatedAdminClientsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/disputes': {
      id: '/_authenticated/admin/disputes'
      path: '/disputes'
      fullPath: '/admin/disputes'
      preLoaderRoute: typeof AuthenticatedAdminDisputesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/documents': {
      id: '/_authenticated/admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AuthenticatedAdminDocumentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/entities': {
      id: '/_authenticated/admin/entities'
      path: '/entities'
      fullPath: '/admin/entities'
      preLoaderRoute: typeof AuthenticatedAdminEntitiesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/spymarket': {
      id: '/_authenticated/admin/spymarket'
      path: '/spymarket'
      fullPath: '/admin/spymarket'
      preLoaderRoute: typeof AuthenticatedAdminSpymarketRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/spymarket-tools': {
      id: '/_authenticated/admin/spymarket-tools'
      path: '/spymarket-tools'
      fullPath: '/admin/spymarket-tools'
      preLoaderRoute: typeof AuthenticatedAdminSpymarketToolsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/wallet': {
      id: '/_authenticated/admin/wallet'
      path: '/wallet'
      fullPath: '/admin/wallet'
      preLoaderRoute: typeof AuthenticatedAdminWalletRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_client/disputes/$id': {
      id: '/_authenticated/_client/disputes/$id'
      path: '/$id'
      fullPath: '/disputes/$id'
      preLoaderRoute: typeof AuthenticatedClientDisputesIdRouteImport
      parentRoute: typeof AuthenticatedClientDisputesRoute
    }
    '/_authenticated/_client/orders/': {
      id: '/_authenticated/_client/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AuthenticatedClientOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/_client/orders/$id': {
      id: '/_authenticated/_client/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AuthenticatedClientOrdersIdRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/_client/orders/import': {
      id: '/_authenticated/_client/orders/import'
      path: '/orders/import'
      fullPath: '/orders/import'
      preLoaderRoute: typeof AuthenticatedClientOrdersImportRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/_client/orders/new': {
      id: '/_authenticated/_client/orders/new'
      path: '/orders/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof AuthenticatedClientOrdersNewRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/_client/quotes/': {
      id: '/_authenticated/_client/quotes/'
      path: '/quotes'
      fullPath: '/quotes/'
      preLoaderRoute: typeof AuthenticatedClientQuotesIndexRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/_client/quotes/$id': {
      id: '/_authenticated/_client/quotes/$id'
      path: '/quotes/$id'
      fullPath: '/quotes/$id'
      preLoaderRoute: typeof AuthenticatedClientQuotesIdRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/_client/quotes/new': {
      id: '/_authenticated/_client/quotes/new'
      path: '/quotes/new'
      fullPath: '/quotes/new'
      preLoaderRoute: typeof AuthenticatedClientQuotesNewRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/_client/workspaces/new': {
      id: '/_authenticated/_client/workspaces/new'
      path: '/new'
      fullPath: '/workspaces/new'
      preLoaderRoute: typeof AuthenticatedClientWorkspacesNewRouteImport
      parentRoute: typeof AuthenticatedClientWorkspacesRoute
    }
    '/_authenticated/admin/disputes/$id': {
      id: '/_authenticated/admin/disputes/$id'
      path: '/$id'
      fullPath: '/admin/disputes/$id'
      preLoaderRoute: typeof AuthenticatedAdminDisputesIdRouteImport
      parentRoute: typeof AuthenticatedAdminDisputesRoute
    }
    '/_authenticated/admin/quotes/': {
      id: '/_authenticated/admin/quotes/'
      path: '/quotes'
      fullPath: '/admin/quotes/'
      preLoaderRoute: typeof AuthenticatedAdminQuotesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/quotes/$id': {
      id: '/_authenticated/admin/quotes/$id'
      path: '/quotes/$id'
      fullPath: '/admin/quotes/$id'
      preLoaderRoute: typeof AuthenticatedAdminQuotesIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/cron/auto-topup': {
      id: '/api/public/cron/auto-topup'
      path: '/api/public/cron/auto-topup'
      fullPath: '/api/public/cron/auto-topup'
      preLoaderRoute: typeof ApiPublicCronAutoTopupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/documents-sweep': {
      id: '/api/public/cron/documents-sweep'
      path: '/api/public/cron/documents-sweep'
      fullPath: '/api/public/cron/documents-sweep'
      preLoaderRoute: typeof ApiPublicCronDocumentsSweepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/order-expiry': {
      id: '/api/public/cron/order-expiry'
      path: '/api/public/cron/order-expiry'
      fullPath: '/api/public/cron/order-expiry'
      preLoaderRoute: typeof ApiPublicCronOrderExpiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedClientDisputesRouteChildren {
  AuthenticatedClientDisputesIdRoute: typeof AuthenticatedClientDisputesIdRoute
}

const AuthenticatedClientDisputesRouteChildren: AuthenticatedClientDisputesRouteChildren =
  {
    AuthenticatedClientDisputesIdRoute: AuthenticatedClientDisputesIdRoute,
  }

const AuthenticatedClientDisputesRouteWithChildren =
  AuthenticatedClientDisputesRoute._addFileChildren(
    AuthenticatedClientDisputesRouteChildren,
  )

interface AuthenticatedClientWorkspacesRouteChildren {
  AuthenticatedClientWorkspacesNewRoute: typeof AuthenticatedClientWorkspacesNewRoute
}

const AuthenticatedClientWorkspacesRouteChildren: AuthenticatedClientWorkspacesRouteChildren =
  {
    AuthenticatedClientWorkspacesNewRoute:
      AuthenticatedClientWorkspacesNewRoute,
  }

const AuthenticatedClientWorkspacesRouteWithChildren =
  AuthenticatedClientWorkspacesRoute._addFileChildren(
    AuthenticatedClientWorkspacesRouteChildren,
  )

interface AuthenticatedClientRouteChildren {
  AuthenticatedClientBillingRoute: typeof AuthenticatedClientBillingRoute
  AuthenticatedClientDashboardRoute: typeof AuthenticatedClientDashboardRoute
  AuthenticatedClientDisputesRoute: typeof AuthenticatedClientDisputesRouteWithChildren
  AuthenticatedClientDocumentsRoute: typeof AuthenticatedClientDocumentsRoute
  AuthenticatedClientProductsRoute: typeof AuthenticatedClientProductsRoute
  AuthenticatedClientSpymarketRoute: typeof AuthenticatedClientSpymarketRoute
  AuthenticatedClientWalletRoute: typeof AuthenticatedClientWalletRoute
  AuthenticatedClientWorkspacesRoute: typeof AuthenticatedClientWorkspacesRouteWithChildren
  AuthenticatedClientOrdersIdRoute: typeof AuthenticatedClientOrdersIdRoute
  AuthenticatedClientOrdersImportRoute: typeof AuthenticatedClientOrdersImportRoute
  AuthenticatedClientOrdersNewRoute: typeof AuthenticatedClientOrdersNewRoute
  AuthenticatedClientQuotesIdRoute: typeof AuthenticatedClientQuotesIdRoute
  AuthenticatedClientQuotesNewRoute: typeof AuthenticatedClientQuotesNewRoute
  AuthenticatedClientOrdersIndexRoute: typeof AuthenticatedClientOrdersIndexRoute
  AuthenticatedClientQuotesIndexRoute: typeof AuthenticatedClientQuotesIndexRoute
}

const AuthenticatedClientRouteChildren: AuthenticatedClientRouteChildren = {
  AuthenticatedClientBillingRoute: AuthenticatedClientBillingRoute,
  AuthenticatedClientDashboardRoute: AuthenticatedClientDashboardRoute,
  AuthenticatedClientDisputesRoute:
    AuthenticatedClientDisputesRouteWithChildren,
  AuthenticatedClientDocumentsRoute: AuthenticatedClientDocumentsRoute,
  AuthenticatedClientProductsRoute: AuthenticatedClientProductsRoute,
  AuthenticatedClientSpymarketRoute: AuthenticatedClientSpymarketRoute,
  AuthenticatedClientWalletRoute: AuthenticatedClientWalletRoute,
  AuthenticatedClientWorkspacesRoute:
    AuthenticatedClientWorkspacesRouteWithChildren,
  AuthenticatedClientOrdersIdRoute: AuthenticatedClientOrdersIdRoute,
  AuthenticatedClientOrdersImportRoute: AuthenticatedClientOrdersImportRoute,
  AuthenticatedClientOrdersNewRoute: AuthenticatedClientOrdersNewRoute,
  AuthenticatedClientQuotesIdRoute: AuthenticatedClientQuotesIdRoute,
  AuthenticatedClientQuotesNewRoute: AuthenticatedClientQuotesNewRoute,
  AuthenticatedClientOrdersIndexRoute: AuthenticatedClientOrdersIndexRoute,
  AuthenticatedClientQuotesIndexRoute: AuthenticatedClientQuotesIndexRoute,
}

const AuthenticatedClientRouteWithChildren =
  AuthenticatedClientRoute._addFileChildren(AuthenticatedClientRouteChildren)

interface AuthenticatedAdminDisputesRouteChildren {
  AuthenticatedAdminDisputesIdRoute: typeof AuthenticatedAdminDisputesIdRoute
}

const AuthenticatedAdminDisputesRouteChildren: AuthenticatedAdminDisputesRouteChildren =
  {
    AuthenticatedAdminDisputesIdRoute: AuthenticatedAdminDisputesIdRoute,
  }

const AuthenticatedAdminDisputesRouteWithChildren =
  AuthenticatedAdminDisputesRoute._addFileChildren(
    AuthenticatedAdminDisputesRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminClientsRoute: typeof AuthenticatedAdminClientsRoute
  AuthenticatedAdminDisputesRoute: typeof AuthenticatedAdminDisputesRouteWithChildren
  AuthenticatedAdminDocumentsRoute: typeof AuthenticatedAdminDocumentsRoute
  AuthenticatedAdminEntitiesRoute: typeof AuthenticatedAdminEntitiesRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminSpymarketRoute: typeof AuthenticatedAdminSpymarketRoute
  AuthenticatedAdminSpymarketToolsRoute: typeof AuthenticatedAdminSpymarketToolsRoute
  AuthenticatedAdminWalletRoute: typeof AuthenticatedAdminWalletRoute
  AuthenticatedAdminQuotesIdRoute: typeof AuthenticatedAdminQuotesIdRoute
  AuthenticatedAdminQuotesIndexRoute: typeof AuthenticatedAdminQuotesIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminClientsRoute: AuthenticatedAdminClientsRoute,
  AuthenticatedAdminDisputesRoute: AuthenticatedAdminDisputesRouteWithChildren,
  AuthenticatedAdminDocumentsRoute: AuthenticatedAdminDocumentsRoute,
  AuthenticatedAdminEntitiesRoute: AuthenticatedAdminEntitiesRoute,
  AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
  AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
  AuthenticatedAdminSpymarketRoute: AuthenticatedAdminSpymarketRoute,
  AuthenticatedAdminSpymarketToolsRoute: AuthenticatedAdminSpymarketToolsRoute,
  AuthenticatedAdminWalletRoute: AuthenticatedAdminWalletRoute,
  AuthenticatedAdminQuotesIdRoute: AuthenticatedAdminQuotesIdRoute,
  AuthenticatedAdminQuotesIndexRoute: AuthenticatedAdminQuotesIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClientRoute: typeof AuthenticatedClientRouteWithChildren
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedPendingRoute: typeof AuthenticatedPendingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClientRoute: AuthenticatedClientRouteWithChildren,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedPendingRoute: AuthenticatedPendingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  ApiPublicCronAutoTopupRoute: ApiPublicCronAutoTopupRoute,
  ApiPublicCronDocumentsSweepRoute: ApiPublicCronDocumentsSweepRoute,
  ApiPublicCronOrderExpiryRoute: ApiPublicCronOrderExpiryRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
